baseURL = 'https://pixel-allydog.github.io/yNsite/'
languageCode = 'zh-cn'
title = 'yNSource'
theme = 'hugo-book'

enableGitInfo = false

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[menu]
# [[menu.before]]
[[menu.after]]
  name = "Github"
  url = "https://github.com/Pixel-ALlydog/yNsite"
  weight = 20

#[[menu.after]]
#  name = "Hugo Themes"
#  url = "https://themes.gohugo.io/hugo-book/"
#  weight = 30

[params]
BookTheme = 'auto'
BookSection = 'docs'
BookToC = true
BookDateFormat = 'Jan 2, 2006'
BookRepo = 'https://github.com/Pixel-ALlydog/yNsite'

